spacetelescope/synphot_refactor

- synphot/models.py
- synphot/spectrum.py
- synphot/utils.py
> Fix RTD import error

- synphot/__init__.py
- synphot/conftest.py
- synphot/integrator.py
- synphot/models.py
- synphot/observation.py
- synphot/reddening.py
- synphot/spectrum.py
- synphot/tests/test_models.py
- synphot/tests/test_observation.py
- synphot/tests/test_reddening.py
- synphot/tests/test_spectrum.py
- synphot/tests/test_thermal.py
- synphot/thermal.py
Fixes #66 
The FWHM part of Gaussian overlaps with astropy/astropy#4936
Applied astropy/package-template#167
Make spectra more compatible with astropy/astropy#3142
> Replace class methods with models

- .travis.yml
- README.rst
- appveyor.yml
- licenses/SIX_LICENSE.rst
- synphot/__init__.py
- synphot/_astropy_init.py
- synphot/binning.py
- synphot/conftest.py
- synphot/extern/setup_package.py
- synphot/extern/six.py
- synphot/models.py
- synphot/observation.py
- synphot/reddening.py
- synphot/setup_package.py
- synphot/specio.py
- synphot/spectrum.py
- synphot/tests/coveragerc
- synphot/tests/test_binning.py
- synphot/tests/test_models.py
- synphot/tests/test_observation.py
- synphot/tests/test_specio.py
- synphot/tests/test_spectrum.py
- synphot/tests/test_thermal.py
- synphot/tests/test_units.py
- synphot/tests/test_utils.py
- synphot/thermal.py
- synphot/units.py
Added `egg_info`, PEP8, and coverage tests. Check for any unclosed files.
> Expand Travis CI tests

- synphot/tests/test_spectrum.py
Added FWHM tests for Gaussian and Box models.
> Added FWHM tests for Gaussian and Box models

- synphot/observation.py
Rearranged keywords for effstim and countrate to be more compatible with astrolib pysynphot.
> Minor effstim API change

- docs/conf.py
- setup.py
- synphot/units.py
Updated `astropy_helpers` to 1.2. Fixed `ConfigParser` compat with Python 3. Fixes #85.
NOTE: Tests failed because of astropy/astropy#5178
> Some updates

- synphot/binning.py
- synphot/models.py
- synphot/observation.py
- synphot/specio.py
- synphot/spectrum.py
- synphot/tests/test_binning.py
- synphot/tests/test_models.py
- synphot/tests/test_observation.py
- synphot/tests/test_reddening.py
- synphot/tests/test_specio.py
- synphot/tests/test_spectrum.py
- synphot/tests/test_thermal.py
- synphot/tests/test_units.py
- synphot/tests/test_utils.py
- synphot/units.py
- synphot/utils.py
Refactored how Quantity is initialized to fix test failure. See astropy/astropy#5178.
> Refactored how Quantity is initialized to fix test failure

- synphot/observation.py
Fix binned wavelengths calculations to handle invalid wavelengths when creating observation.
> Fix binned wavelengths

- synphot/reddening.py
Always extrapolate extinction curve, to be compatible with ASTROLIB version.
> Always extrapolate extinction curve

- synphot/specio.py
- synphot/tests/test_observation.py
- synphot/tests/test_reddening.py
- synphot/tests/test_specio.py
- synphot/tests/test_spectrum.py
Removed the need to specifically provide encoding to read commonly supported data.
> Change default data encoding to binary

- synphot/observation.py
- synphot/spectrum.py
- synphot/tests/test_spectrum.py
Added a method to properly extrapolate an empirical spectrum and added tests. Fixed normalization requiring extrapolation.
>  Fixed normalization requiring extrapolation

- synphot/models.py
- synphot/reddening.py
- synphot/spectrum.py
- synphot/tests/test_models.py
- synphot/tests/test_spectrum.py
Empirical model now extrapolates like ASTROLIB PYSYNPHOT by default. Fix bug in extrapolation logic. Updated tests.
> Empirical model now extrapolates like ASTROLIB PYSYNPHOT by default

- synphot/models.py
- synphot/tests/test_models.py
- synphot/tests/test_spectrum.py
Fixed `Box1D` model's `sampleset` to cover end point properly.
> Fixed Box1D sampleset

- synphot/spectrum.py
- synphot/tests/test_spectrum.py
Make check overlap to be consistent with ASTROLIB PYSYNPHOT.
> Make check overlap to be consistent with ASTROLIB PYSYNPHOT

- synphot/models.py
- synphot/tests/test_spectrum.py
Fixes #110. Also see astropy/astropy#5417.
> Updated Empirical1D to changes in Tabular1D

- synphot/_astropy_init.py
- synphot/models.py
Now that  astropy/astropy#5391 and astropy/astropy#5393 are merged, things can be simplified a little.
Note: Does not affect `stsynphot` portion of the codes.
> Updated models to be consistent with Astropy dev

- synphot/spectrum.py
Improve `plot()` method with Quantity. The code was written when Quantity was not supported by `matplotlib` but things have changed.
> Improve plot method with Quantity

- synphot/spectrum.py
- synphot/tests/test_spectrum.py
Implement `truediv` for spectrum objects since Astropy modeling supports it.
> Implement truediv for spectrum objects 

- synphot/spectrum.py
- synphot/tests/test_spectrum.py
Expanded division to handle two sources. This is a follow up of #116.
> Expanded division to handle two sources

- docs/synphot/overview.rst
- docs/synphot/spectrum.rst
- synphot/spectrum.py
- synphot/tests/test_spectrum.py
Implemented redshift with option to conserve flux. Added tests and doc. Fixes #68.
> Implemented redshift with option to conserve flux

- docs/index.rst
- docs/synphot/overview.rst
- docs/synphot/spectrum.rst
- docs/synphot/tutorials.rst
- synphot/reddening.py
- synphot/tests/test_reddening.py
Added Lyman-alpha extinction as provided by @dancoe. Fixes #77.
> Added Lyman-alpha extinction

- ah_bootstrap.py
- ez_setup.py
This is an automated update of the astropy-helpers submodule to v2.0.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*
> Update astropy-helpers to v2.0.2

- .travis.yml
- appveyor.yml
- setup.cfg
- synphot/conftest.py
#139 broke `coveralls` reporting on Travis.
> Fix coveralls

- CITATION
- MANIFEST.in
- docs/index.rst
- docs/synphot/from_pysyn_iraf.rst
- setup.cfg
* Add citation file
* Fix #152
> DOC: Add citation and update help

- synphot/tests/test_spectrum.py
- synphot/tests/test_units.py
- synphot/units.py
> BUG: Fix scalar unit conversion for VEGAMAG

- .travis.yml
- README.rst
> Use codecov for coverage report

- docs/index.rst
- synphot/tests/test_units.py
> DOC: Clarify conda install

- CHANGES.rst
- docs/index.rst
- synphot/tests/test_utils.py
- synphot/utils.py
> Download helper function

- synphot/tests/test_utils.py
> Fix download_data test bug

- azure-pipelines.yml
> [WIP] Azure CI 

- docs/index.rst
In response to #188 and my own confusion, I've reworded the section on downloading data for using the pre-defined standard star, extinction laws, and bandpasses in the docs.
> Reworded the bit about downloading data for pre-defined quantities

- synphot/models.py
Like spacetelescope/pysynphot#115
> DOC: Replace textnormal with mathrm

- azure-templates.yml
> TST: Fix Azure

- docs/index.rst
Linkcheck fix from @sean-lockwood and install update.
> Fix links in doc and update installation instruction

- ah_bootstrap.py
- docs/conf.py
- setup.cfg
- setup.py
Some warnings seen on install. Follow up of #203
> Fix helpers deprecation warnings

- .bandit.yaml
- azure-pipelines.yml
Security audit with `bandit`.
**TODO**
> MNT: Security audit

- azure-pipelines.yml
- docs/conf.py
- docs/index.rst
- docs/synphot/bandpass.rst
- docs/synphot/c_ext.rst
- docs/synphot/formulae.rst
- docs/synphot/from_pysyn_iraf.rst
- docs/synphot/observation.rst
- docs/synphot/overview.rst
- docs/synphot/spectrum.rst
- docs/synphot/tutorials.rst
- docs/synphot/units.rst
- setup.cfg
- synphot/models.py
- synphot/tests/test_models.py
- synphot/tests/test_observation.py
- synphot/tests/test_reddening.py
- synphot/tests/test_specio.py
- synphot/tests/test_spectrum.py
Fix #150 
Address part of #195
> Add linkcheck and doctest

- setup.cfg
- synphot/tests/setup_package.py
> Fix tests package data declaration

- MANIFEST.in
> Fix MANIFEST syntax

- azure-pipelines.yml
- azure-templates.yml
- setup.cfg
Need this for the next PR to come.
> MNT: Simplify dep installations

- CHANGES.rst
- azure-pipelines.yml
- azure-templates.yml
- docs/conf.py
- docs/index.rst
- docs/synphot/bandpass.rst
- docs/synphot/spectrum.rst
- setup.cfg
- synphot/compat.py
- synphot/conftest.py
- synphot/spectrum.py
- synphot/tests/test_spectrum.py
> ENH: specutils bridge

- CITATION.md
- README.rst
> DOC: Add Zenodo badge

- docs/synphot/tutorials.rst
> DOC: Special area for XMM-OM

- azure-pipelines.yml
- setup.cfg
- synphot/spectrum.py
- synphot/tests/test_binning.py
- synphot/tests/test_models.py
- synphot/tests/test_observation.py
- synphot/tests/test_reddening.py
- synphot/tests/test_specio.py
- synphot/tests/test_spectrum_bandpass.py
- synphot/tests/test_spectrum_misc.py
- synphot/tests/test_spectrum_source.py
- synphot/tests/test_thermal.py
- synphot/tests/test_utils.py
> TST: test_spectrum.py antithrust settlement

- synphot/blackbody.py
- synphot/models.py
- synphot/spectrum.py
- synphot/tests/test_reddening.py
Fix #259
Note: Checked `stsynphot` too but found nothing there.
> MNT: Use to_value when appropriate

- docs/index.rst
> DOC: Example to set config for entire session

- synphot/units.py
Fix #262 
Is this clearer, @ariedel ?
> DOC: Clarify vegaspec in convert_flux

- CITATION.md
- README.rst
> MNT: Use https

- docs/index.rst
Will add back when things are less confusing, maybe.
Also see spacetelescope/stsynphot_refactor#127
> DOC: Remove confusing mention of JWST

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/dependabot.yml
- .github/labeler.yml
- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/open_actions.yml
> TST: Add CodeQL check, workflow/template updates

- .github/workflows/ci_workflows.yml
This pull request is to enable strict twine check in CI.
> TST: Strict twine check

- .github/workflows/ci_workflows.yml
- setup.cfg
- synphot/setup_package.py
- synphot/tests/test_binning.py
- tox.ini
This pull request is to use tox to run CI.
Fixes #230 , similar to spacetelescope/stsynphot_refactor#134
Encountered https://stackoverflow.com/questions/57426346/running-tox-with-c-extension-module ?
> TST: Use tox to run CI

- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
This pull request is to allow skipping CI without failing the job.
> TST: Allow skip CI without fail

- synphot/reddening.py
- synphot/tests/test_binning.py
This pull request is to address compatibility with Numpy 1.20 to avoid DeprecationWarning.
> MNT: Replace np.float with float

- .github/labeler.yml
This pull request is to add `tox.ini` to labeler rule.
> MNT: Update Action labeler rule

- tox.ini
They changed default branch name.
> TST: Change specutils default branch

- .github/labeler.yml
- docs/index.rst
- docs/synphot/config.rst
> DOC: Fix synphot.cfg mentions

- synphot/compat.py
- synphot/models.py
This pull request is to restore compatibility with `astropy` 4.3.dev caused by astropy/astropy#11204
> MNT: Compat with astropy 4.3.dev

- .github/workflows/ci_workflows.yml
https://www.reddit.com/r/linux4noobs/comments/ducn4k/how_to_fix_404_not_found_ip_911899583_80/
https://linuxconfig.org/how-to-list-and-remove-ppa-repository-on-ubuntu-18-04-bionic-beaver-linux
```
2021-06-07T13:22:40.1651415Z The following NEW packages will be installed:
2021-06-07T13:22:40.1676549Z   libxml2-utils
2021-06-07T13:22:40.1846840Z 0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
2021-06-07T13:22:40.3868661Z Need to get 107 kB of archives.
2021-06-07T13:22:40.3870008Z After this operation, 180 kB of additional disk space will be used.
2021-06-07T13:22:40.3874294Z Err:1 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 libxml2-utils amd64 2.9.10+dfsg-5+ubuntu16.04.1+deb.sury.org+3
2021-06-07T13:22:40.3876608Z   404  Not Found [IP: 91.189.95.85 80] …
```
> TST: Fix IP not found for sudo

- .github/workflows/publish-to-pypi.yml
This pull request is to see why release failed.
> Hot wheels

- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/publish-to-pypi.yml
- CHANGES.rst
- docs/synphot/filter_par.rst
- setup.cfg
- synphot/compat.py
- synphot/filter_parameterization/filter_fft.py
- synphot/models.py
- synphot/spectrum.py
- synphot/tests/test_spectrum_misc.py
- synphot/tests/test_spectrum_source.py
- synphot/units.py
- tox.ini
This pull request is to go with https://github.com/spacetelescope/stsynphot_refactor/pull/167
> MNT: Bump required deps, update workflows

- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/open_actions.yml
- .github/workflows/predeps_workflow.yml
- tox.ini
This pull request is to pin to `tox<4` (has breaking changes) and add RC testing workflow.
> TST: Pin to tox<4

- tox.ini
the `codecov` package is now deprecated and has been yanked from PyPI
> remove usages of deprecated `codecov` package

- .github/workflows/ci_workflows.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/predeps_workflow.yml
- .github/workflows/publish-to-pypi.yml
- tox.ini
This pull request is to fix #364
> TST: Bump checkout version and add Python 3.12

- .github/workflows/publish-to-pypi.yml
- CHANGES.rst
Add more archs to wheels and re-enable testing on all archs. 🤞
> BLD: Add more archs to wheels
