synphot/tests/test_observation.py

`obs.effstim()` tests now test for mag results using `atol` and not `rtol`, as per my back of envelop calculations on the treatments between flux and mag thingies.

Update effstim tests

---

synphot/observation.py
synphot/spectrum.py
synphot/tests/test_observation.py
synphot/tests/test_spectrum.py

`__call__` now can handle flux unit conversion. Default flux unit now ties directly to internal flux unit (but does not change existing behavior). Also, some code clean up.

__call__ to perform unit conversion

---

synphot/models.py
synphot/observation.py
synphot/reddening.py
synphot/spectrum.py
synphot/tests/test_models.py
synphot/tests/test_observation.py
synphot/tests/test_reddening.py
synphot/tests/test_spectrum.py
synphot/thermal.py

Use new `TabularModel` in Astropy, as implemented in astropy/astropy#5105. Also see spacetelescope/gwcs#28.
TODO:

Use new Tabular model in Astropy

---

synphot/models.py
synphot/reddening.py
synphot/spectrum.py
synphot/tests/test_models.py
synphot/tests/test_spectrum.py

Implement extrapolation that is like ASTROLIB PYSYNPHOT. It requires Scipy's `interpn` to behave like `(method='nearest', fill_value=None)` *but* only for extrapolated values, not interpolated values (`method='linear'`).

Implement extrapolation that is like ASTROLIB PYSYNPHOT

---

synphot/spectrum.py

Do not discard negative throughput, to be consistent with ASTROLIB PYSYNPHOT.

Keep negative throughput in bandpass

---

synphot/__init__.py
synphot/conftest.py
synphot/observation.py

Deprecate EFFLPHOT properly. Import models and genwave util to synphot namespace.

Deprecate EFFLPHOT properly

---

synphot/observation.py
synphot/spectrum.py

Fix a small bug where `Observation` is created with irrelevant bandpass metadata still attached. Should not affect any existing API or results.

Clean up metadata when creating Observation

---

synphot/specio.py
synphot/tests/test_reddening.py
synphot/tests/test_specio.py
synphot/tests/test_spectrum.py

Replaced `clobber` keyword with `overwrite` for FITS I/O to be consistent with Astropy 1.3 and to avoid deprecation warnings.

Replaced clobber with overwrite

---

.travis.yml
appveyor.yml
setup.cfg
setup.py
synphot/_astropy_init.py
synphot/tests/test_binning.py
synphot/tests/test_models.py
synphot/tests/test_observation.py
synphot/tests/test_reddening.py
synphot/tests/test_specio.py
synphot/tests/test_spectrum.py
synphot/tests/test_thermal.py
synphot/tests/test_units.py
synphot/tests/test_utils.py

Use system `pytest` and update `astropy-helpers`. Will need a release to include this fix for Astropy v2.

Use system pytest and update astropy-helpers

---

synphot/tests/test_models.py
synphot/tests/test_spectrum.py
synphot/tests/test_thermal.py

Fix #125 
Use old constants for tests to maintain backward compatibility with `astrolib` results. This is using the recommended solution in astropy/astropy#6383.

Fix failed tests due to Astropy constants update

---

synphot/models.py

The goal of this is not the correct fix, but a minimal fix to avoid conflicts galore with some big refactoring that I have been working on on-and-off for months. Should not affect anything with Astropy 2.x and will fix error with Astropy 3.x.

Remove dependency on BaseGaussian1D from astropy

---

CHANGES.rst
docs/index.rst
docs/synphot/from_pysyn_iraf.rst
docs/synphot/spectrum.rst
docs/synphot/tutorials.rst
synphot/models.py
synphot/spectrum.py
synphot/tests/test_observation.py
synphot/tests/test_spectrum.py

Fix #153 
@mkelley , are you interested to review before I merge?

Fix gauss total_flux unit handling

---

CHANGES.rst
docs/synphot/formulae.rst
docs/synphot/observation.rst
synphot/observation.py
synphot/tests/test_observation.py

Fix #159
I can't say I understand why PHOTNU needs a special logic block. I tried converting from PHOTLAM and FLAM using bandpass pivot (like what is done with FNU etc) but it didn't work out. At least all the supported flux units give values consistent with PySynphot now (in my limited testing). 
Results *before* the fix: https://gist.github.com/pllim/2d053b327d384c587b0297950644e7d1
Results *after* the fix: https://gist.github.com/pllim/c378494302ad4df095fe506df8ae8ade
**TODO**
cc @deustua @tddesjardins @bhilbert4 (Tyler, do you want to take this for a spin?)

Make effstim calculation consistent with PySynphot

---

azure-pipelines.yml
azure-templates.yml
synphot/compat.py
synphot/models.py
synphot/spectrum.py
synphot/tests/test_models.py
synphot/tests/test_spectrum.py

Ensure `synphot` still works with astropy/astropy#8769.
**TODO**

MNT: Compatibility with new models in astropy 4.0dev

---

synphot/spectrum.py

This is to work around astropy/astropy#9141 .

Explicitly provide unit on np.insert

---

synphot/config.py
synphot/synphot.cfg
synphot/tests/test_observation.py
synphot/tests/test_spectrum.py
synphot/tests/test_utils.py

I see that  `alpha_lyr_stis_009.fits` was made available in 2019-09-06.
@ibusko , is ETC using that one yet?

MNT: Bump Vega data version

---

synphot/observation.py
synphot/tests/test_observation.py

This pr is to address the issue [206](https://github.com/spacetelescope/synphot_refactor/issues/206)
EDIT: Fixes #206

Raise proper exception when spectrum is not passed

---

synphot/__init__.py

To avoid what happened to `stsynphot` 0.2.2 `conda-forge` release to repeat here. Same patch as spacetelescope/stsynphot_refactor#104

MNT: To avoid setuptools in conda-forge run requirements

---

CHANGES.rst
docs/index.rst
docs/synphot/overview.rst
setup.cfg
synphot/blackbody.py
synphot/compat.py
synphot/models.py
synphot/spectrum.py
synphot/tests/test_blackbody.py
synphot/tests/test_models.py
synphot/tests/test_spectrum.py
synphot/tests/test_thermal.py

To be fully compatible with `astropy` 4.0 without all the deprecation warnings.
Fix #223 
Close #224 
xref astropy/astropy#9282 and astropy/astropy#9445
**TODO**

MNT: Un-deprecate blackbody and add RickerWavelet1D

---

CHANGES.rst
docs/index.rst
synphot/synphot.cfg
synphot/tests/test_utils.py
synphot/utils.py

This PR closes #208 by making it possible to use the astropy download cache.  
One caveat: There are no unit tests.  I started trying to make one but then realized it's not clear to me that we can really test this properly without accidentally messing with the users' "true" cache.  The related tests in astropy test the cache machinery by downloading a "fake" file and then clearing just that file, but here we can't do it because we actually want the *correct* file.  So that's awkward. I can concoct some sort of complicated scheme like what we *used* to have in astropy where we fake the cache location, run the test, and then un-fake it, but that seems like it might be overkill for this.  @pllim do you agree and/or have a simpler idea for how I might test this?  Or alternatively I can add a …

add option for download_data to use the astropy cache

---

CHANGES.rst
docs/synphot/observation.rst
synphot/observation.py
synphot/tests/test_observation.py
synphot/tests/test_spectrum.py

Observation to take Spectrum1D as source

---

CHANGES.rst
docs/conf.py
docs/synphot/spectrum.rst
docs/synphot/tutorials.rst
setup.cfg
synphot/compat.py
synphot/models.py
synphot/reddening.py
synphot/tests/test_reddening.py

Fix #132 
p.s. Sorry, Karl, no `__mul__` magic needed after all. 😉 
**TODO**

ENH: Integrate with dust-extinction API

---

CHANGES.rst
docs/index.rst
docs/synphot/overview.rst
docs/synphot/spectrum.rst
synphot/compat.py
synphot/config.py
synphot/models.py
synphot/observation.py
synphot/spectrum.py
synphot/tests/test_integrator.py
synphot/tests/test_spectrum.py
synphot/tests/test_units.py
synphot/tests/test_utils.py
synphot/units.py

[ENH] Analytic integrals

---

CHANGES.rst
synphot/config.py
synphot/synphot.cfg
synphot/tests/test_observation.py
synphot/tests/test_spectrum_source.py
synphot/tests/test_utils.py

Fix #258 . This makes `synphot` in-sync with what is advertised at https://archive.stsci.edu/hlsps/reference-atlases/cdbs/current_calspec/ as of May 2020.
**TODO**

MNT: Update default Vega

---

docs/synphot/spectrum.rst

Not sure why now RTD fails with this:
```
from .../docs/synphot/spectrum.rst:
TypeError: float() argument must be a string or a number, not 'Parameter'
```

Fix RTD plotting TypeError

---

docs/index.rst
synphot/config.py
synphot/synphot.cfg
synphot/utils.py

Address the code changes for #270
Companion to spacetelescope/stsynphot_refactor#121 and spacetelescope/pysynphot#135

Change CDBS to TRDS

---

.github/workflows/publish-to-pypi.yml

Previously the publication action was not compatible with the PEP517 build that is required by this project.

Re-enable automatic publication to PyPI

---

README.rst

Very minor edit - I noticed the readme CI badge doesn't have a target, which means if you click on it you get just the badge.  I *think* this is now the right target.

add a target for the CI badge

---

.github/workflows/publish-to-pypi.yml
conftest.py

This pull request is to implement releasing wheels.
Fixes #294 
**TODO**

Update publishing workflow to use wheels

---

tox.ini

This is an automated update made by the `batchpr` tool :robot: to because `astropy` has changed its default branch! You can report issues to @pllim.

MNT: Update astropy default branch

---

synphot/tests/test_binning.py
synphot/tests/test_blackbody.py
synphot/tests/test_integrator.py
synphot/tests/test_models.py
synphot/tests/test_observation.py
synphot/tests/test_reddening.py
synphot/tests/test_specio.py
synphot/tests/test_spectrum_bandpass.py
synphot/tests/test_spectrum_misc.py
synphot/tests/test_spectrum_source.py
synphot/tests/test_thermal.py
synphot/tests/test_units.py
synphot/tests/test_utils.py

This PR contains only those changes from https://github.com/spacetelescope/synphot_refactor/pull/310 that pertain to switching unit tests from relative to absolute imports.
The changes to `tox.ini` will be addressed in https://github.com/spacetelescope/synphot_refactor/pull/310

Use absolute imports in unit tests

---

setup.cfg
synphot/tests/test_observation.py

The outdated usage was throwing an extra warning about `distutils` locally and was failing the test unnecessarily.

TST: Fix outdated catch_warnings usage

---

CHANGES.rst
docs/synphot/spectrum.rst
synphot/observation.py
synphot/tests/test_units.py
synphot/units.py

This pull request is to fix #327 
*This is breaking change!* Unit string will change from, say, `'VEGAMAG'` to `'mag(VEGA)'`. Also the behavior also changes because it is now a magnitude object, not just "plain Quantity."
- Contacted them on 2022-05-17
- Response from Adric: *I tried it on some of our regression tests that use vegamags and abmags (we have none that use OBmags). Our multimission/normalization and jwst/workbooks test suites all passed without complaint. Pandeia is compatible with your change... I think the PR is OK to merge. It passes all the relevant tests.* (2022-05-23)
<details>
@mhvk , I am trying to follow your advice at https://github.com/astropy/astropy/pull/13158#discussion_r858962549 but I am unable to get the new magnitude definitions to work with existing unit …

Separate VEGAMAG and OBMAG

---

synphot/tests/test_observation.py

Numpy data (written with `ndarray.tofile()` are usually system dependent; at least they depend on the byte order. This makes the `test_countrate_neg_leak()` [fail on big endian platforms (IBM zSystems/s390x)](https://buildd.debian.org/status/fetch.php?pkg=synphot&arch=s390x&ver=1.1.1-2&stamp=1658536121&raw=0). This patch enforces little endian on all platforms with `np.fromfile()` so the test passes there as well. With this patch, [the package passes on s390x](https://buildd.debian.org/status/fetch.php?pkg=synphot&arch=s390x&ver=1.1.1-3&stamp=1658641250&raw=0).

Enforce little endian when reading Numpy test data file

---

docs/index.rst

I noticed that the docs ask for Python >=3.8 while AstroConda is only compatible with Python <=3.7. As such, the installation option that uses the AstroConda channel doesn't work.
If you like this change, I can propose the same one for `stsynphot`.

Remove AstroConda installation instructions

---

.github/workflows/ci_workflows.yml
.github/workflows/predeps_workflow.yml
synphot/binning.py
synphot/blackbody.py
synphot/models.py
synphot/observation.py
synphot/reddening.py
synphot/specio.py
synphot/spectrum.py
synphot/thermal.py
synphot/units.py
synphot/utils.py
tox.ini

This pull request is to fix #344
Also other changes to be consistent with https://github.com/spacetelescope/stsynphot_refactor/pull/173

TST: Unpin tox

---

CHANGES.rst
synphot/models.py
synphot/tests/test_spectrum_misc.py

This pull request is to address #340. Adds step input to Box1D model while preserving prior behavior as default and adds covering unit test. 
Fixes #340

Modifying Box1D model to allow step input 

---

.github/workflows/ci_workflows.yml
setup.cfg
synphot/blackbody.py
synphot/specio.py

This pull request is to:
* Handle astropy/astropy#14439
* Fix #349

Remove pytest-openfiles, fix unit string comparison in doctests

---

.github/workflows/publish-to-pypi.yml
CHANGES.rst

This pull request is to add OSX ARM64 wheel to the release process. I decided not to switch to OpenAstronomy workflow. I already have something that works and I don't see much value right now to switch to something I cannot control.
Fixes #351

Add OSX ARM64 wheel

---

.readthedocs.yaml
docs/conf.py

RTD no longer supports any `system_packages` setting: https://blog.readthedocs.com/drop-support-system-packages/
This PR removes the unused `system_packages` setting

remove unsupported `system_packages` RTD config setting

---

.github/workflows/ci_workflows.yml
.readthedocs.yaml
CHANGES.rst
conftest.py
docs/index.rst
pyproject.toml
setup.cfg
synphot/observation.py
synphot/spectrum.py
synphot/tests/test_integrator.py
synphot/tests/test_units.py
tox.ini

This pull request is to fix #362 and any resulting modernization that has to happen.

MNT: NumPy 2.0 compatibility, other fixes

---

synphot/filter_parameterization/filter_fft.py

This pull request is to keep up with continuous numpy 2.0.dev changes upstream. Something new every day.

MNT: ptp was removed from the ndarray class in NumPy 2.0

---

.github/workflows/publish-to-pypi.yml

Hi, version 4 of upload-artifact and download-artifact were recently released.
Staying on old version is not viable long term because GitHub will sooner or later drop support for the old versions of node that these depend on.
Since migration to v4 is not as straightfoward as bumping the version number, I'm helping all astropy-related packages byt manually performing the necessary changes.

MNT: upgrade upload/download-artifact GitHub actions

---

setup.cfg

`filter_par.rst` result is from numpy<2 and needs to be updated when we run it with numpy>=2
Fixes #374

TST: filter_par.rst result is from numpy<2

---

CHANGES.rst
docs/synphot/overview.rst
synphot/reddening.py
synphot/specio.py
synphot/spectrum.py
synphot/tests/test_binning.py
synphot/tests/test_reddening.py
synphot/tests/test_specio.py
synphot/tests/test_spectrum_misc.py
synphot/tests/test_utils.py
synphot/thermal.py
synphot/units.py

This pull request is to address the problem of `read_fits_spec` unnecessarily hardcoding `TUNIT1` and `TUNIT2`. However, in making it more flexible, some breaking changes are unavoidable. See change log added here.
Fixes #372

BUG/API: read_fits_spec now more flexible but at a cost

---

.github/workflows/ci_workflows.yml
.github/workflows/codeql-analysis.yml
.github/workflows/predeps_workflow.yml
CHANGES.rst
docs/index.rst
pyproject.toml
setup.cfg
synphot/blackbody.py
synphot/compat.py
synphot/models.py
tox.ini

This pull request is to address impending numpy 2.0 release.
Fixes #386

MNT: numpy 2 and astropy 6.1 compat, bump minversions

---

.github/workflows/ci_workflows.yml
.github/workflows/publish-to-pypi.yml
docs/synphot/filter_par.rst
pyproject.toml
setup.cfg
tox.ini

This pull request is to
* fix #376 
* address first 2 items in #393

Python 3.13 support

---

.github/workflows/check_milestone.yml
.github/workflows/ci_workflows.yml
.github/workflows/codeql-analysis.yml
.github/workflows/open_actions.yml
.github/workflows/predeps_workflow.yml
.github/workflows/publish-to-pypi.yml

As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)

MNT: Use hash for Action workflow versions and update if needed

---

.github/workflows/ci_workflows.yml

As recommended by actions/runner-images#11101 , this PR replaces the deprecated ubuntu-20.04 runner with a newer version. This also replaces RTD workflow, if applicable, to future-proof the build in case it follows suit.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/63)

MNT: Replace ubuntu-20.04 with ubuntu-22.04

---

CHANGES.rst
docs/synphot/bandpass.rst
docs/synphot/observation.rst
docs/synphot/spectrum.rst
setup.cfg
synphot/compat_specutils.py
synphot/observation.py
synphot/spectrum.py
synphot/tests/test_spectrum_bandpass.py
synphot/tests/test_spectrum_source.py
tox.ini

This pull request is to fix https://github.com/spacetelescope/synphot_refactor/issues/411

MNT: Compatibility with specutils 2.0
